interface PerksData{
  id:number,
  key:string,
  name:string,
  icon:string
}

export const PerksMeta:{[x:number]:PerksData} = {
  8000: {
    id: 8000,
    key: 'Precision',
    name: '정밀',
    icon: 'perk-images/Styles/7201_Precision.png',
  },
  8005: {
    id: 8005,
    key: 'PressTheAttack',
    name: '집중 공격',
    icon: 'perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png',
  },
  8008: {
    id: 8008,
    key: 'LethalTempo',
    name: '치명적 속도',
    icon: 'perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png',
  },
  8009: {
    id: 8009,
    key: 'PresenceOfMind',
    name: '침착',
    icon: 'perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png',
  },
  8010: {
    id: 8010,
    key: 'Conqueror',
    name: '정복자',
    icon: 'perk-images/Styles/Precision/Conqueror/Conqueror.png',
  },
  8014: {
    id: 8014,
    key: 'CoupDeGrace',
    name: '최후의 일격',
    icon: 'perk-images/Styles/Precision/CoupDeGrace/CoupDeGrace.png',
  },
  8017: {
    id: 8017,
    key: 'CutDown',
    name: '체력차 극복',
    icon: 'perk-images/Styles/Precision/CutDown/CutDown.png',
  },
  8021: {
    id: 8021,
    key: 'FleetFootwork',
    name: '기민한 발놀림',
    icon: 'perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png',
  },
  8100: {
    id: 8100,
    key: 'Domination',
    name: '지배',
    icon: 'perk-images/Styles/7200_Domination.png',
  },
  8105: {
    id: 8105,
    key: 'RelentlessHunter',
    name: '끈질긴 사냥꾼',
    icon: 'perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png',
  },
  8106: {
    id: 8106,
    key: 'UltimateHunter',
    name: '궁극의 사냥꾼',
    icon: 'perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png',
  },
  8112: {
    id: 8112,
    key: 'Electrocute',
    name: '감전',
    icon: 'perk-images/Styles/Domination/Electrocute/Electrocute.png',
  },
  8120: {
    id: 8120,
    key: 'GhostPoro',
    name: '유령 포로',
    icon: 'perk-images/Styles/Domination/GhostPoro/GhostPoro.png',
  },
  8124: {
    id: 8124,
    key: 'Predator',
    name: '포식자',
    icon: 'perk-images/Styles/Domination/Predator/Predator.png',
  },
  8126: {
    id: 8126,
    key: 'CheapShot',
    name: '비열한 한 방',
    icon: 'perk-images/Styles/Domination/CheapShot/CheapShot.png',
  },
  8128: {
    id: 8128,
    key: 'DarkHarvest',
    name: '어둠의 수확',
    icon: 'perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png',
  },
  8134: {
    id: 8134,
    key: 'IngeniousHunter',
    name: '영리한 사냥꾼',
    icon: 'perk-images/Styles/Domination/IngeniousHunter/IngeniousHunter.png',
  },
  8135: {
    id: 8135,
    key: 'RavenousHunter',
    name: '굶주린 사냥꾼',
    icon: 'perk-images/Styles/Domination/RavenousHunter/RavenousHunter.png',
  },
  8136: {
    id: 8136,
    key: 'ZombieWard',
    name: '좀비 와드',
    icon: 'perk-images/Styles/Domination/ZombieWard/ZombieWard.png',
  },
  8138: {
    id: 8138,
    key: 'EyeballCollection',
    name: '사냥의 증표',
    icon: 'perk-images/Styles/Domination/EyeballCollection/EyeballCollection.png',
  },
  8139: {
    id: 8139,
    key: 'TasteOfBlood',
    name: '피의 맛',
    icon: 'perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png',
  },
  8143: {
    id: 8143,
    key: 'SuddenImpact',
    name: '돌발 일격',
    icon: 'perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png',
  },
  8200: {
    id: 8200,
    key: 'Sorcery',
    name: '마법',
    icon: 'perk-images/Styles/7202_Sorcery.png',
  },
  8210: {
    id: 8210,
    key: 'Transcendence',
    name: '깨달음',
    icon: 'perk-images/Styles/Sorcery/Transcendence/Transcendence.png',
  },
  8214: {
    id: 8214,
    key: 'SummonAery',
    name: '콩콩이 소환',
    icon: 'perk-images/Styles/Sorcery/SummonAery/SummonAery.png',
  },
  8224: {
    id: 8224,
    key: 'NullifyingOrb',
    name: '무효화 구체',
    icon: 'perk-images/Styles/Sorcery/NullifyingOrb/Pokeshield.png',
  },
  8226: {
    id: 8226,
    key: 'ManaflowBand',
    name: '마나순환 팔찌',
    icon: 'perk-images/Styles/Sorcery/ManaflowBand/ManaflowBand.png',
  },
  8229: {
    id: 8229,
    key: 'ArcaneComet',
    name: '신비로운 유성',
    icon: 'perk-images/Styles/Sorcery/ArcaneComet/ArcaneComet.png',
  },
  8230: {
    id: 8230,
    key: 'PhaseRush',
    name: '난입',
    icon: 'perk-images/Styles/Sorcery/PhaseRush/PhaseRush.png',
  },
  8232: {
    id: 8232,
    key: 'Waterwalking',
    name: '물 위를 걷는 자',
    icon: 'perk-images/Styles/Sorcery/Waterwalking/Waterwalking.png',
  },
  8233: {
    id: 8233,
    key: 'AbsoluteFocus',
    name: '절대 집중',
    icon: 'perk-images/Styles/Sorcery/AbsoluteFocus/AbsoluteFocus.png',
  },
  8234: {
    id: 8234,
    key: 'Celerity',
    name: '기민함',
    icon: 'perk-images/Styles/Sorcery/Celerity/CelerityTemp.png',
  },
  8236: {
    id: 8236,
    key: 'GatheringStorm',
    name: '폭풍의 결집',
    icon: 'perk-images/Styles/Sorcery/GatheringStorm/GatheringStorm.png',
  },
  8237: {
    id: 8237,
    key: 'Scorch',
    name: '주문 작열',
    icon: 'perk-images/Styles/Sorcery/Scorch/Scorch.png',
  },
  8242: {
    id: 8242,
    key: 'Unflinching',
    name: '불굴의 의지',
    icon: 'perk-images/Styles/Sorcery/Unflinching/Unflinching.png',
  },
  8275: {
    id: 8275,
    key: 'NimbusCloak',
    name: '빛의 망토',
    icon: 'perk-images/Styles/Sorcery/NimbusCloak/6361.png',
  },
  8299: {
    id: 8299,
    key: 'LastStand',
    name: '최후의 저항',
    icon: 'perk-images/Styles/Sorcery/LastStand/LastStand.png',
  },
  8300: {
    id: 8300,
    key: 'Inspiration',
    name: '영감',
    icon: 'perk-images/Styles/7203_Whimsy.png',
  },
  8304: {
    id: 8304,
    key: 'MagicalFootwear',
    name: '마법의 신발',
    icon: 'perk-images/Styles/Inspiration/MagicalFootwear/MagicalFootwear.png',
  },
  8306: {
    id: 8306,
    key: 'HextechFlashtraption',
    name: '마법공학 점멸기',
    icon: 'perk-images/Styles/Inspiration/HextechFlashtraption/HextechFlashtraption.png',
  },
  8313: {
    id: 8313,
    key: 'PerfectTiming',
    name: '완벽한 타이밍',
    icon: 'perk-images/Styles/Inspiration/PerfectTiming/PerfectTiming.png',
  },
  8316: {
    id: 8316,
    key: 'MinionDematerializer',
    name: '미니언 해체분석기',
    icon: 'perk-images/Styles/Inspiration/MinionDematerializer/MinionDematerializer.png',
  },
  8321: {
    id: 8321,
    key: 'FuturesMarket',
    name: '외상',
    icon: 'perk-images/Styles/Inspiration/FuturesMarket/FuturesMarket.png',
  },
  8345: {
    id: 8345,
    key: 'BiscuitDelivery',
    name: '비스킷 배달',
    icon: 'perk-images/Styles/Inspiration/BiscuitDelivery/BiscuitDelivery.png',
  },
  8347: {
    id: 8347,
    key: 'CosmicInsight',
    name: '우주적 통찰력',
    icon: 'perk-images/Styles/Inspiration/CosmicInsight/CosmicInsight.png',
  },
  8351: {
    id: 8351,
    key: 'GlacialAugment',
    name: '빙결 강화',
    icon: 'perk-images/Styles/Inspiration/GlacialAugment/GlacialAugment.png',
  },
  8352: {
    id: 8352,
    key: 'TimeWarpTonic',
    name: '시간 왜곡 물약',
    icon: 'perk-images/Styles/Inspiration/TimeWarpTonic/TimeWarpTonic.png',
  },
  8358: {
    id: 8358,
    key: 'MasterKey',
    name: '프로토타입: 만능의 돌',
    icon: 'perk-images/Styles/Inspiration/MasterKey/MasterKey.png',
  },
  8360: {
    id: 8360,
    key: 'UnsealedSpellbook',
    name: '봉인 풀린 주문서',
    icon: 'perk-images/Styles/Inspiration/UnsealedSpellbook/UnsealedSpellbook.png',
  },
  8400: {
    id: 8400,
    key: 'Resolve',
    name: '결의',
    icon: 'perk-images/Styles/7204_Resolve.png',
  },
  8401: {
    id: 8401,
    key: 'ShieldBash',
    name: '보호막 강타',
    icon: 'perk-images/Styles/Resolve/MirrorShell/MirrorShell.png',
  },
  8410: {
    id: 8410,
    key: 'ApproachVelocity',
    name: '쾌속 접근',
    icon: 'perk-images/Styles/Resolve/ApproachVelocity/ApproachVelocity.png',
  },
  8429: {
    id: 8429,
    key: 'Conditioning',
    name: '사전 준비',
    icon: 'perk-images/Styles/Resolve/Conditioning/Conditioning.png',
  },
  8437: {
    id: 8437,
    key: 'GraspOfTheUndying',
    name: '착취의 손아귀',
    icon: 'perk-images/Styles/Resolve/GraspOfTheUndying/GraspOfTheUndying.png',
  },
  8439: {
    id: 8439,
    key: 'Aftershock',
    name: '여진',
    icon: 'perk-images/Styles/Resolve/VeteranAftershock/VeteranAftershock.png',
  },
  8444: {
    id: 8444,
    key: 'SecondWind',
    name: '재생의 바람',
    icon: 'perk-images/Styles/Resolve/SecondWind/SecondWind.png',
  },
  8446: {
    id: 8446,
    key: 'Demolish',
    name: '철거',
    icon: 'perk-images/Styles/Resolve/Demolish/Demolish.png',
  },
  8451: {
    id: 8451,
    key: 'Overgrowth',
    name: '과잉성장',
    icon: 'perk-images/Styles/Resolve/Overgrowth/Overgrowth.png',
  },
  8453: {
    id: 8453,
    key: 'Revitalize',
    name: '소생',
    icon: 'perk-images/Styles/Resolve/Revitalize/Revitalize.png',
  },
  8463: {
    id: 8463,
    key: 'FontOfLife',
    name: '생명의 샘',
    icon: 'perk-images/Styles/Resolve/FontOfLife/FontOfLife.png',
  },
  8465: {
    id: 8465,
    key: 'Guardian',
    name: '수호자',
    icon: 'perk-images/Styles/Resolve/Guardian/Guardian.png',
  },
  8473: {
    id: 8473,
    key: 'BonePlating',
    name: '뼈 방패',
    icon: 'perk-images/Styles/Resolve/BonePlating/BonePlating.png',
  },
  9101: {
    id: 9101,
    key: 'Overheal',
    name: '과다치유',
    icon: 'perk-images/Styles/Precision/Overheal.png',
  },
  9103: {
    id: 9103,
    key: 'LegendBloodline',
    name: '전설: 핏빛 길',
    icon: 'perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png',
  },
  9104: {
    id: 9104,
    key: 'LegendAlacrity',
    name: '전설: 민첩함',
    icon: 'perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png',
  },
  9105: {
    id: 9105,
    key: 'LegendTenacity',
    name: '전설: 강인함',
    icon: 'perk-images/Styles/Precision/LegendTenacity/LegendTenacity.png',
  },
  9111: {
    id: 9111,
    key: 'Triumph',
    name: '승전보',
    icon: 'perk-images/Styles/Precision/Triumph.png',
  },
  9923: {
    id: 9923,
    key: 'HailOfBlades',
    name: '칼날비',
    icon: 'perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png',
  },
};

export default PerksMeta;
